services:
  ocr-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/hajtran/docker-ocr:latest
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./output:/app/output
